-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PRODUCTS TABLE
create table products (
  id text primary key,
  name text not null,
  tagline text,
  description text,
  price text,
  image text,
  specs text[],
  badge text,
  is_new boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ORDERS TABLE
create table orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text not null,
  email text not null,
  phone text not null,
  address text not null,
  city text,
  postal_code text,
  payment_method text,
  total_amount numeric not null,
  status text default 'pending'
);

-- ORDER ITEMS TABLE
create table order_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  order_id bigint references orders(id) on delete cascade,
  product_id text references products(id),
  product_name text,
  quantity integer not null,
  price numeric not null
);

-- SERVICE REQUESTS TABLE
create table service_requests (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  phone text,
  service_type text,
  message text
);

-- CONTACT MESSAGES TABLE
create table contact_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  subject text,
  message text
);

-- SEED DATA FOR PRODUCTS
insert into products (id, name, tagline, description, price, image, specs, badge, is_new) values
('m1', 'MTEL M1', 'Compact. Reliable. Powerful.', 'Compact and reliable smartphone with essential features for everyday use.', '3,299', '/src/assets/m1-render.png', ARRAY['1.77" Display', '1000mAh Battery', 'FM Radio', 'Bluetooth', 'Dual Sim'], 'Best Seller', false),
('m10', 'MTEL M10', 'Advanced smartphone with larger display.', 'High-performance Processor, High-speed 5G.', 'Coming Soon', '/src/assets/m10-render.png', ARRAY['2.4" Display', '2500mAh Battery', 'FM Radio', 'Bluetooth', 'Triple Sim'], 'Coming Soon', true),
('m1-type-c', 'MTEL M1 Type-C', 'The classic M1, now upgraded.', 'Now upgraded with Type-C charging and call recording.', 'Coming Soon', '/src/assets/m1-typec.png', ARRAY['1.77" Display', '1020mAh Battery', 'Type-C Port', 'Call Recording'], 'New Edition', true);
